autoload/zettel/vimwiki.vim, ftplugin/vimwiki.vim
This PR introduces two commands:
- ZettelGenerateIndex
- ZettelGenerateTags
They are based on their Vimwiki counterparts, the difference being that the links are named using the `%title` attribute instead of the file name. 
If there is interest in this PR, I could add a few more comments before merging.
=> Index generation

README.md, autoload/zettel/vimwiki.vim, ftplugin/vimwiki.vim
Hello,
Thank you for developing this plugin. Would you be interested in considering my modification? It allows the filename to be appended with the title, and if there is no title passed it won't append it. It is just easier for me when I am searching my notes to give me more context into what the note was for. 
If you would be interested in this modification, I can fine-tune it and add a global variable so this behaviour is user-set through a config variable.
Let me know your thoughts,
- Hristo
=> Add option to Name Zettel Note filename by title

autoload/zettel/vimwiki.vim, ftplugin/vimwiki.vim
This changes some things around:
- Generated filenames use global replace for spaces, instead of first occurrence only.
- Save newly generated file after adding custom front-matter to it.
- Fix `[[` only working at the end of lines.
- Make `[[` leave you in insert mode after adding the link (makes `[[` more like a real autocomplete)
In order to accomplish these I needed to change the behavior for pages without titles. Previously, you would go to insert mode and be able to type a title. Now, for consistency, you are always placed in insert mode at the end of the link. If a page doesn't have a title, the wiki filename is used as the link text.
=> Minor improvements to UX

ftplugin/vimwiki.vim
After playing with the old pull request I noticed it works in terminal vim but not in MacVim. In MacVim, the first keystroke is erroneously treated as a normal mode keystroke (so, e.g. `j` would move the cursor down normally but then immediately place you into insert mode). Looks like this is related, even though it refers to nvim: https://github.com/junegunn/fzf/issues/426
The same workaround there works here, in both terminal vim and macvim.
=> use feedkeys instead of startinsert

ftplugin/vimwiki.vim
Issue: when inserting a link in the middle of a line of text, the cursor is incorrectly positioned on the character AFTER the link.
Steps to reproduce: From terminal vim in normal mode, type `oxx<Esc>i[[<CR>Z<Esc>`
Expected result: `x[some link](2020...)Zx`
Actual result: `x[some link](2020...)xZ`
For reference, here's the steps to expected behavior when inserting a link at the end of a line.
Steps to reproduce: From terminal vim in normal mode, type `oxx[[<CR>Z<Esc>`
Expected result: `xx[some link](2020...)Z`
Actual result: as expected
=> Reposition cursor before appending text

ftplugin/vimwiki.vim
Using this method means that the search results will favor the text in
the file over the file name. Which makes the results more accurate.
=> Breaks ties with match closest to end of line

autoload/zettel/vimwiki.vim
The current dev branch of vimwiki introduced some breaking changes in their interface and tags handling. This commit adpts vim-zettel to this changes.
=> fix for breaking changes in the current vimwiki dev branch

autoload/zettel/vimwiki.vim
vimwiki lets you define a `links_space_char` setting (:h
links_space_char), which lets you specify the separators used in place
of spaces for filenames. vim-zettel, before this patch, simply used `_`
to replace spaces in generated filenames. Now it respects the
`link_space_char` setting.
---
This is a backwards incompatible change, so feel free to reject (or
suggest a work around, like perhaps defining a custom vim-zettel setting
for example).
=> Respect `links_space_char` setting from vimwiki

autoload/zettel/vimwiki.vim
My vimwiki path has a space in it, which breaks the command invocation when grepping for backlinks.  This properly escapes the vimwiki path before building the search command.
=> Escapes wikipath when doing backlinks to handle spaces.

autoload/zettel/vimwiki.vim
Now generates random on vim releases prior to 8.2 without depending on lua.
Fixes #81.
=> Make #vimwiki#make_random_chars compatible to Vim 8.1

autoload/zettel/fzf.vim, autoload/zettel/vimwiki.vim
When a file in a subfolder is open and `:ZettelNew` is invoked, vim-zettel opens a file in that directory and saves it, and then opens the same filename in the root of the wiki and saves _that_ file, resulting in the same file written to two different locations.
This change forces the create function to always operate in the root to prevent this behavior. I believe this might be an example of a "load bearing bug" and people might have their workflows now relying on the counter-intuitive behavior, so I'd understand choosing to not to change the behavior. I'm sure there are better approaches to solving this, and I'm uncertain if there are other use cases within vim-zettel that this might negatively impact, but this does correct `:ZettelNew`'s behavior against what I think its expectations …
=> Prevent duplicate file creation

autoload/zettel/vimwiki.vim, doc/zettel.txt, ftplugin/vimwiki/zettel.vim, plugin/zettel.vim
Hi
thanks for the great plugin :-) . I would have suggestions regarding the creation of new Zettels and the logic to which directory to save a new Zettel / vimwiki-file. 
**Currently**, ZettelNew works only if a vimwiki file is open (active buffer). It saves the new Zettel in the directory of the active vimwiki-buffer, in case this directory is specified as `path` in one of the `vimwiki_list` dictionaries. 
1. I have missed to create new Zettels out of the blue, e.g. as first action entering vim/neovim (i.e. empty buffer). I **suggest** to allow ZettelNew to work without active vimwiki-file. 
2. Additionally, I propose the following logical order to save the newly created wiki-file in: 
(1) the current directory if it is in the `g:vimwiki_list` paths (similar to current behaviour)
(2) if …
=> ZettelNew: run on non-vimwiki-buffer and directory to save new Zettel to

ftplugin/vimwiki/zettel.vim
Hi!
When I leave the vimwiki buffer and start editing, say, `.lua` file, the `[[` mapping still exists.
In `lua`, `[[` is used for defining unescaped string.
I don't know whether the mapping is intended to be used outside `vimwiki` files or not, so it might not suit the case if we implement buffer-local mapping.
If that's the case, please let me know!
Thanks 😄
=> Change default mappings to buffer local mappings

autoload/zettel/vimwiki.vim
The change was in
vimwiki/vimwiki@dede5a1eeaa13474beedd07427ad2869ebe4ca7a to allow it to
work on the current wiki or a range of lines
This change ensures it runs _only_ on the current vimwiki, as was the
case before the API change.
=> Match the changed API of vimwiki#base#check_links

ftplugin/vimwiki/zettel.vim
Change the default mapping to their noremap counterparts to avoid conflicts with user defined mappings. This fixes #85.
=> Change default mapping to noremap mode

ftplugin/vimwiki/zettel.vim
At least in ViM (I'm still stuck on 8.2 here) it seems you cannot create a mapping from a key to a <Plug> with "noremap", they need to be the regular version.
=> Fix mappings to <Plug> in ViM

autoload/zettel/vimwiki.vim
Currently, when checking whether we are in the wiki or not the comparison will only return true if we are in the root of the wiki, since the comparison is exact folder to folder. Check instead if the path of the wiki is contained in the path of the current file. Move the comments to the appropriate path of the conditional.
=> fix incorrect path comparison

tests/README.md, tests/resources/templ.tpl, tests/rtp.vim, tests/test_vimrc, tests/zettel_creation.vader
This pull-request adds a test framework based on [vader.vim](https://github.com/junegunn/vader.vim).
I've setup a dedicated minimal `.vimrc` to isolate test runs from the wikis specified in the user `g:vimwiki_list`.
A detailed explanation of how to run the tests can be found in `tests/README.md`.
I've set up only a few tests for:
- zettel creation
- replacement of highlighted text with link (markdown) 
- zettel creation with/without user defined template and frontmatter
I hope this can be a first step in helping others adding new functionalities, without breaking anything.
=> Add a test framework based on vader.vim

autoload/zettel/vimwiki.vim
When using extension containing multiple dots, for example `.wiki.txt`, generated links would be faulty links by ending with piece of the extension, for example `.wiki`, then vimwiki would try to go to a file that ends with `.wiki.wiki.txt` instead.
This patch solves the issue by removing the exact suffix of the extension instead of using the root filename modifier.
=> Fix link generation when wiki extension has multiple dots

autoload/zettel/fzf.vim
Directly use the wiki extension setting instead of removing last dot.
Set wiki extension to `.wiki.txt`:
```
let g:vimwiki_list = [{
\"path": $REDACTED."/Wiki",
\"path_html": $REDACTED."/Wiki_html",
\'template_path': $REDACTED."/Wiki_html_assets",
\'template_default': 'default',
\'template_ext': '.html',
\'generated_links_caption': 1,
\'auto_export': 1,
\'auto_toc': 0,
\'auto_diary_index': 1,
\'auto_generate_links': 1,
\'auto_generate_tags': 1,
\'maxhi': 1,
\'syntax': 'default',
\'ext': '.wiki.txt',
\'index': 'index',
\'auto_tags': 1}]
```
Create a note with filename "2024-04-30.wiki.txt"
Edit another wiki note, in insert mode  `[[` search for previous note to insert a link.
Link inserted `[[2024-04-30.wiki|Content]]` does not work
Link inserted `[[2024-04-30|Content]]` works
=> Fix erronerous links with extention contains dot

autoload/zettel/vimwiki.vim
The prior logic would place the rel_path in the link name, making the path and link name identical. Remove this behavior to make the link name match the text as it was highlighted.
=> Correctly format link name in zettel_new_selected()

autoload/zettel/vimwiki.vim, doc/zettel.txt
I cut corners here by:
1. assuming grepprg is not vimgrep
2. assuming grepprg is compatible with grep (-l, -r, etc.)
Here I profile the time spent in zettel#vimwiki#backlinks on my personal wiki folder:
- before: backlinks takes 1.170s
- after:  backlinks takes 0.096s
- 
fixes https://github.com/michal-h21/vim-zettel/issues/154
=> RFC: use external grep
